# Generated by Django 4.0 on 2022-01-01 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra', models.CharField(max_length=45)),
                ('naziv', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='BankarskiRacun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_racuna', models.CharField(max_length=45)),
                ('banka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likvidatura.banka')),
            ],
        ),
        migrations.CreateModel(
            name='DnevnoStanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_izvoda', models.IntegerField()),
                ('datum_izvoda', models.DateField()),
                ('novo_stanje', models.FloatField()),
                ('prethodno_stanje', models.FloatField()),
                ('promet_na_teret', models.FloatField()),
                ('promet_u_korist', models.FloatField()),
                ('rezervisano', models.FloatField()),
                ('bankarski_racun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likvidatura.bankarskiracun')),
            ],
        ),
        migrations.CreateModel(
            name='IzlaznaFaktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_fakture', models.CharField(max_length=45)),
                ('iznos_za_placanje', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PoslovnaGodina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.IntegerField()),
                ('zakljucena', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PoslovniPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=45)),
                ('bankarski_racun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likvidatura.bankarskiracun')),
            ],
        ),
        migrations.CreateModel(
            name='Preduzece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=45)),
                ('pib', models.CharField(max_length=45)),
                ('maticni_broj', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='StavkaIzvoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_stavke', models.IntegerField()),
                ('iznos', models.FloatField()),
                ('model', models.IntegerField()),
                ('poziv_na_broj', models.CharField(max_length=45)),
                ('primalac', models.CharField(max_length=45)),
                ('racun_primaoca', models.CharField(max_length=45)),
                ('svrha_placanja', models.CharField(max_length=45)),
                ('dnevno_stanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likvidatura.dnevnostanje')),
                ('duznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likvidatura.poslovnipartner')),
            ],
        ),
    ]
