# Generated by Django 4.0 on 2022-01-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likvidatura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankarskiracun',
            name='preduzece',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='likvidatura.preduzece'),
        ),
        migrations.AddField(
            model_name='izlaznafaktura',
            name='poslovna_godina_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='likvidatura.poslovnagodina'),
        ),
        migrations.AddField(
            model_name='poslovnagodina',
            name='preduzece',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='likvidatura.preduzece'),
        ),
        migrations.AlterField(
            model_name='bankarskiracun',
            name='banka_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='likvidatura.banka'),
        ),
        migrations.AlterField(
            model_name='dnevnostanje',
            name='bankarski_racun_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='likvidatura.bankarskiracun'),
        ),
        migrations.AlterField(
            model_name='poslovnipartner',
            name='bankarski_racun_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='likvidatura.bankarskiracun'),
        ),
        migrations.AlterField(
            model_name='stavkaizvoda',
            name='dnevno_stanje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='likvidatura.dnevnostanje'),
        ),
        migrations.AlterField(
            model_name='stavkaizvoda',
            name='duznik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='likvidatura.poslovnipartner'),
        ),
    ]
