# Generated by Django 4.0 on 2022-01-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likvidatura', '0002_bankarskiracun_preduzece_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stavkaizvoda',
            name='fakture',
            field=models.ManyToManyField(to='likvidatura.IzlaznaFaktura'),
        ),
        migrations.AlterField(
            model_name='stavkaizvoda',
            name='dnevno_stanje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likvidatura.dnevnostanje'),
        ),
    ]
