# Generated by Django 4.0 on 2022-01-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likvidatura', '0003_stavkaizvoda_fakture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izlaznafaktura',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
