# Generated by Django 4.0 on 2022-01-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likvidatura', '0004_alter_izlaznafaktura_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izlaznafaktura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
