# Generated by Django 4.0 on 2022-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likvidatura', '0005_alter_izlaznafaktura_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnevnostanje',
            name='stavke',
            field=models.ManyToManyField(related_name='stavke', to='likvidatura.StavkaIzvoda'),
        ),
    ]
