# Generated by Django 4.0 on 2022-01-11 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likvidatura', '0006_dnevnostanje_stavke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnevnostanje',
            name='stavke',
        ),
        migrations.AlterField(
            model_name='stavkaizvoda',
            name='dnevno_stanje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='likvidatura.dnevnostanje'),
        ),
    ]
