# Generated by Django 4.0 on 2022-01-14 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likvidatura', '0007_remove_dnevnostanje_stavke_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnevnostanje',
            name='bankarski_racun_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stanja', to='likvidatura.bankarskiracun'),
        ),
    ]
