# Generated by Django 4.0 on 2022-01-14 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likvidatura', '0008_alter_dnevnostanje_bankarski_racun_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stavkaizvoda',
            name='fakture',
        ),
        migrations.AlterField(
            model_name='stavkaizvoda',
            name='dnevno_stanje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='likvidatura.dnevnostanje'),
        ),
    ]
