# Generated by Django 4.0 on 2022-01-14 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likvidatura', '0009_remove_stavkaizvoda_fakture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakljuceneFakture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uplaceno', models.FloatField()),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likvidatura.izlaznafaktura')),
                ('stavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likvidatura.stavkaizvoda')),
            ],
        ),
    ]
