# Generated by Django 4.0 on 2022-01-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likvidatura', '0010_zakljucenefakture'),
    ]

    operations = [
        migrations.AddField(
            model_name='izlaznafaktura',
            name='uplaceno',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stavkaizvoda',
            name='preostalo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='zakljucenefakture',
            name='uplaceno',
            field=models.FloatField(default=0),
        ),
    ]
