# Generated by Django 4.0 on 2022-01-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likvidatura', '0013_banka_version_bankarskiracun_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banka',
            name='version',
        ),
        migrations.RemoveField(
            model_name='bankarskiracun',
            name='version',
        ),
        migrations.RemoveField(
            model_name='dnevnostanje',
            name='version',
        ),
        migrations.RemoveField(
            model_name='poslovnagodina',
            name='version',
        ),
        migrations.RemoveField(
            model_name='poslovnipartner',
            name='version',
        ),
        migrations.RemoveField(
            model_name='preduzece',
            name='version',
        ),
    ]
